PORT: 1337

COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

PATHS:
  dist: "dist"
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  icons:
    - "bower_components/font-awesome/fonts/fontawesome-webfont.*"
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/font-awesome/scss"
  javascript:
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/what-input/what-input.js"
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    - "bower_components/granim/dist/granim.min.js"
    - "src/assets/js/!(app).js"
    - "src/assets/js/app.js"
